# Generated by Django 3.0.2 on 2020-01-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('desg', models.CharField(max_length=20)),
                ('quali', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Faculty',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Slot',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcode', models.CharField(max_length=10)),
                ('subname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='TT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=3)),
                ('semsec', models.CharField(max_length=2)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TT', to='api.Faculty')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TT', to='api.Slot')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TT', to='api.Subject')),
            ],
            options={
                'db_table': 'TT',
            },
        ),
    ]
