# Generated by Django 3.0.2 on 2020-01-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tt',
            name='room',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
