# Generated by Django 3.0.2 on 2020-01-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='fid',
            field=models.CharField(default=None, max_length=6),
            preserve_default=False,
        ),
    ]
