# Generated by Django 3.0.2 on 2020-01-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_faculty_fid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pid',
        ),
        migrations.AddField(
            model_name='profile',
            name='semsec',
            field=models.CharField(default='5A', max_length=2),
            preserve_default=False,
        ),
    ]
