# Generated by Django 3.0.2 on 2020-01-17 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test1', models.IntegerField(blank=True, default=None, null=True)),
                ('Test2', models.IntegerField(blank=True, default=None, null=True)),
                ('Test3', models.IntegerField(blank=True, default=None, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Marks', to='api.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Marks',
            },
        ),
    ]
