# Generated by Django 2.2.3 on 2020-02-14 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profile_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='LAB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=3)),
                ('semsec', models.CharField(max_length=2)),
                ('batch', models.CharField(max_length=2)),
                ('faculty1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LAB1', to='api.Faculty')),
                ('faculty2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LAB2', to='api.Faculty')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LAB', to='api.Slot')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LAB', to='api.Subject')),
            ],
            options={
                'db_table': 'LAB',
            },
        ),
    ]
