version: "3.7"
services:
  front:
    image: rottiakash/bitcse-frontend
    container_name: bitcse-frontend
    networks:
      - bitcse
  back:
    image: rottiakash/bitcse-backend
    volumes: 
      - ./backend:/app
  loadbal:
    image: rottiakash/bitcse-loadbal
    networks: 
      - bitcse
    volumes: 
      - ./backend/bit.sock:/app/bit.sock
    ports: 
      - 80:80
    depends_on: 
      - "back"
networks: 
  bitcse: